spring.application.name=backend

# Conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/fidelizacion
spring.datasource.username=fidelizacion_app
spring.datasource.password=${DB_PASSWORD}

# Hibernate no toca las tablas; las gestionaremos nosotros
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=true